name: ajay
location: gwalior
dob: 10/03/1991

tools:
  - git
  - github
  - docker

tools: [git, github, docker]  

hobbies:
  - teaching
  - reading
  - workouts

experiences:
  devops:
    linux: 2
    docker: 2
    kubernetes: 1.5
    git: 3
    github: 3
    terrforms: 0.6

experiences:
  - devops:
      linux: 2
      docker: 2
  - backend:
      java: 3

experiences:
  devops: {linux: 2, docker: 2, kubernetes: 1.5, git: 3, github: 3, terrforms: 0.6}    

  
